# GENERATE TIME: 2025-12-08
# CMD: basicsr/train.py -opt options/train/train_PMDAN_conv_x4_SA_Safe.yml

# general settings
name: PMDAN_SMDA_only_x4_safe
model_type: SRModel
scale: 4
num_gpu: 1
manual_seed: 0

# dataset and data loader settings
datasets:
  train:
    name: DF2K
    type: PairedImageDataset
    # 路径保持不变
    dataroot_gt: /home/user2/ycw/data/train_data/DF2K_sub/HR
    dataroot_lq: /home/user2/ycw/data/train_data/DF2K_sub/LR_bicubic/LRx4
    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 256
    use_hflip: true
    use_rot: true

    # data loader
    num_worker_per_gpu: 8
    batch_size_per_gpu: 16
    dataset_enlarge_ratio: 10
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: Set5
    type: PairedImageDataset
    dataroot_gt: /home/user2/ycw/data/test_data/set5/mod4/GT
    dataroot_lq: /home/user2/ycw/data/test_data/set5/mod4/LRx4
    io_backend:
      type: disk

# network structures
network_g:
  type: PMDAN_conv
  in_channels: 3
  num_feat: 56
  num_block: 8
  out_channels: 3
  upscale: 4

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  accumulate_grad: 2
  use_amp: true
  grad_clip: 0.5

  ema_decay: 0.999
  optim_g:
    type: Adam
    lr: !!float 5e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [1000000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 1000000
  warmup_iter: 5000

  # losses
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

# validation settings
val:
  val_freq: !!float 5e3
  save_img: true

  metrics:
    PSNR:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
      better: higher
    SSIM:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true
      better: higher

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 5e3
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500